import type { Metadata } from "next";
import "./globals.css";
import { createAppConfig } from "@/lib/app_config/create";
import ClientBootstrap from "@/app/client_bootstrap";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Create the AppConfig on the server to be read on the client.
  const appConfig = await createAppConfig();
  return (
    <html lang="en">
      <body className="antialiased">
        <ClientBootstrap appConfig={appConfig}>{children}</ClientBootstrap>
      </body>
    </html>
  );
}
